### PR TITLE
Added English documentation

### PR DESCRIPTION
**Pull request by pronskiy**

### CODE REVIEW

**Comment by pronskiy** [comment]
Fixes #4

**Comment by younes0** [comment]
:+1:

**Comment by Heart1010** [comment]
There are many "broken" things in there (from the translated text imho) like a space after every $ and so on... this should be corrected imho.

**Comment by pronskiy** [comment]
@Heart1010 which spaces you mean? Here is my fork https://github.com/pronskiy/DiDOM, could you please point out example of broken things?
The translation may be not correct 100%, but this is better than nothing imo.

**Comment by Heart1010** [comment]
@pronskiy Sorry, my fault... the text I saw in "Files changed" tab view here on github was automated google translated (and here the extra spaces were in). But double checked again so this auto translate was off, now everything is looking good :+1:

**Comment by pronskiy** [comment]
@Heart1010 no problem, thanks for checking! 👌

**Comment by Imangazaliev** [comment]
Thank you

**Pull request merged**
