### PR TITLE
Update from phpunit 4.8 to ^9

### PR DESCRIPTION
**Pull request by 8ctopus**
Hi again!

I've updated all tests from phpunit 4.8 to phpunit 9.5.1.

Running the tests with phpunit 9.5.1 gives:

```bash
root@3bbb953af872:/test# vendor/bin/phpunit tests
PHPUnit 9.5.1 by Sebastian Bergmann and contributors.

...............................................................  63 / 413 ( 15%)
............................................................... 126 / 413 ( 30%)
............................................................... 189 / 413 ( 45%)
...........................R................................... 252 / 413 ( 61%)
............................................................... 315 / 413 ( 76%)
............................................................... 378 / 413 ( 91%)
...................................                             413 / 413 (100%)

Time: 00:00.204, Memory: 8.00 MB

There was 1 risky test:

1) DiDom\Tests\ElementTest::testReplaceWithElementFromAnotherDocument
This test did not perform any assertions

/test/tests/ElementTest.php:2120

OK, but incomplete, skipped, or risky tests!
Tests: 413, Assertions: 843, Risky: 1.
```

I didn't touch the only issue `testReplaceWithElementFromAnotherDocument` as I'm not sure what to do.

### CODE REVIEW

**Comment by Imangazaliev** [comment]
PHPUnit 5 requires PHP 5.6 and higher but DiDom minimum version is 5.4, so the update will break Travis CI.

**Comment by 8ctopus** [comment]
For those who use obsolete php versions like 5.4 (released 01 Mar 2012) they can use `composer require imangazaliev/didom 1.16.1`. Or maybe I don't understand the problem?

**Comment by 8ctopus** [comment]
@Imangazaliev Can you please explain? you can reply in Russian if easier (что я не понимаю?)

**Comment by Imangazaliev** [comment]
> For those who use obsolete php versions like 5.4 (released 01 Mar 2012) they can use ...

Yes, but I'm planning to make some fixes and add some feature that I want to be supported by the older versions. I think that updating of PHPUnit this is not enough reason to make this breaking change.

By the way I'm planning to develop and release `v2` that will include all breaking changes, in shaa Allah.

**Comment by 8ctopus** [comment]
Got it, thanks for the explanation.

**Pull request closed without merging**
